image: node:18

pipelines:
  default:
    - step:
        name: "Install & Test"
        caches:
          - node
        script:
          - yarn install --frozen-lockfile
          - yarn lint
          - yarn build

    - step:
        name: "Docker Build & Push to ECR"
        services:
          - docker
        script:
          - echo "Logging in to Docker Hub..."
          - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin  

          - echo "Building Docker image..."
          - docker build -t $DOCKER_HUB_USERNAME/nest-app:latest .
          - echo "Pushing Docker image to ECR..."
          - docker push $DOCKER_HUB_USERNAME/nest-app:latest

    - step:
        name: "Deploy to EC2 (Staging)"
        deployment: staging
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: ec2-user
              SERVER: $STAGING_HOST
              COMMAND: |
                cd /home/ec2-user/app
                docker-compose pull service
                docker-compose down service
                docker-compose up --build -d service
